import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = resolve(root, '.env');

const env = {};
if (existsSync(envPath)) {
  readFileSync(envPath, 'utf8').split('\n').forEach(line => {
    line = line.trim();
    if (!line || line.startsWith('#')) return;
    const idx = line.indexOf('=');
    if (idx === -1) return;
    env[line.slice(0, idx).trim()] = line.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
  });
}

const {
  VITE_FIREBASE_API_KEY = '',
  VITE_FIREBASE_AUTH_DOMAIN = '',
  VITE_FIREBASE_PROJECT_ID = '',
  VITE_FIREBASE_STORAGE_BUCKET = '',
  VITE_FIREBASE_MESSAGING_SENDER_ID = '',
  VITE_FIREBASE_APP_ID = '',
} = env;

if (!VITE_FIREBASE_PROJECT_ID) {
  console.warn('⚠  .env missing or incomplete — firebase-messaging-sw.js will be a stub');
}

const sw = `// Auto-generated by scripts/generate-fcm-sw.mjs — do not edit manually
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.0/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: "${VITE_FIREBASE_API_KEY}",
  authDomain: "${VITE_FIREBASE_AUTH_DOMAIN}",
  projectId: "${VITE_FIREBASE_PROJECT_ID}",
  storageBucket: "${VITE_FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${VITE_FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${VITE_FIREBASE_APP_ID}",
});

const messaging = firebase.messaging();

// Background message handler (app closed / hidden tab)
messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || 'RistaSetu';
  const body  = payload.notification?.body  || '';
  const url   = payload.data?.url || '/';

  self.registration.showNotification(title, {
    body,
    icon: '/icons/icon-192.png',
    badge: '/icons/icon-72.png',
    data: { url },
    requireInteraction: false,
  });
});

// Tap on notification → open / focus app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = event.notification.data?.url || '/';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clientList => {
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      return clients.openWindow(url);
    })
  );
});
`;

writeFileSync(resolve(root, 'public/firebase-messaging-sw.js'), sw);
console.log('✓ firebase-messaging-sw.js generated');
